'use client';

/**
 * Copyright (c) VA360 LABS S.L.
 * SPDX-License-Identifier: LicenseRef-Didacta-Sustainable-Use
 */

import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { authStorage } from '@/lib/auth-storage';
import {
  academyApi,
  onboardingApi,
  ONBOARDING_STEPS,
  PASOS_OBLIGATORIOS,
  VACIO,
  type Academy,
  type OnboardingProgress,
  type OnboardingStep,
} from '@/lib/academy';
import { publishThemeUpdate, themingApi, type TenantTheme } from '@/lib/theming';

/** Pasos que se resuelven en otra pantalla del panel, no aquí dentro. */
const DESTINOS: Partial<Record<OnboardingStep, string>> = {
  curso: '/admin/cursos',
  alumnos: '/admin/usuarios/invitar',
  cobros: '/admin/billing',
  correo: '/admin/emails',
};

/**
 * Asistente de puesta en marcha de la academia.
 *
 * Bloqueante por decisión de producto, pero **sólo `nombre` y `marca` son
 * obligatorios**: son los que evitan que un cliente acabe con una academia
 * llamada como su correo y con el aspecto por defecto. Lo demás —primer curso,
 * invitar alumnos, cobros, correo propio— lleva «ahora no», porque una academia
 * recién comprada legítimamente todavía no tiene alumnos ni cursos, y dejar a
 * alguien encerrado aquí por eso sería peor que no tener asistente.
 *
 * El progreso se guarda en el servidor a cada paso (ver `onboardingApi`), no al
 * final: si se cae la conexión en el paso 7, no se pierden los seis anteriores.
 */
export default function BienvenidaPage() {
  const router = useRouter();
  const t = useTranslations('bienvenida');

  const [cargando, setCargando] = useState(true);
  const [progreso, setProgreso] = useState<OnboardingProgress>(VACIO);
  const [academia, setAcademia] = useState<Academy | null>(null);
  const [theme, setTheme] = useState<TenantTheme | null>(null);
  const [nombre, setNombre] = useState('');
  const [hue, setHue] = useState(213);
  const [guardando, setGuardando] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiado, setCopiado] = useState(false);

  const paso = progreso.step;
  const indice = ONBOARDING_STEPS.indexOf(paso);

  useEffect(() => {
    const token = authStorage.getAccessToken();
    if (!token) {
      router.replace('/signin');
      return;
    }
    let cancelado = false;
    void (async () => {
      const [prog, aca, th] = await Promise.all([
        onboardingApi.read(),
        academyApi.getMine(token).catch(() => null),
        themingApi.getMine(token).catch(() => null),
      ]);
      if (cancelado) return;
      // Ya lo hizo (o lo hizo el otro admin de la academia): no se repite.
      if (prog.completedAt) {
        router.replace('/inicio');
        return;
      }
      setProgreso(prog);
      setAcademia(aca);
      setTheme(th);
      // El nombre autogenerado NO se precarga: si lo dejamos escrito, basta con
      // darle a continuar para quedarse con «valen.ayesa» sin enterarse.
      setNombre(aca && !aca.looksAutogenerated ? aca.name : '');
      if (th) setHue(th.brandHue);
      setCargando(false);
    })();
    return () => {
      cancelado = true;
    };
  }, [router]);

  const persistir = useCallback(async (siguiente: OnboardingProgress) => {
    setProgreso(siguiente);
    try {
      await onboardingApi.write(siguiente);
    } catch {
      // Que no se pueda guardar el progreso no debe cortar el asistente: lo
      // peor que pasa es que al volver empiece antes de donde estaba.
    }
  }, []);

  const irA = useCallback(
    (destino: OnboardingStep, marcar?: { done?: boolean; skipped?: boolean }) => {
      const done = new Set(progreso.done);
      const skipped = new Set(progreso.skipped);
      if (marcar?.done) {
        done.add(paso);
        skipped.delete(paso);
      }
      if (marcar?.skipped) {
        skipped.add(paso);
        done.delete(paso);
      }
      void persistir({
        ...progreso,
        step: destino,
        done: [...done],
        skipped: [...skipped],
      });
      setError(null);
    },
    [paso, progreso, persistir],
  );

  const avanzar = useCallback(
    (marcar?: { done?: boolean; skipped?: boolean }) => {
      const siguiente = ONBOARDING_STEPS[Math.min(indice + 1, ONBOARDING_STEPS.length - 1)]!;
      irA(siguiente, marcar);
    },
    [indice, irA],
  );

  const retroceder = useCallback(() => {
    irA(ONBOARDING_STEPS[Math.max(indice - 1, 0)]!);
  }, [indice, irA]);

  const guardarNombre = useCallback(async () => {
    const limpio = nombre.trim();
    if (!limpio) {
      setError(t('nombreVacio'));
      return;
    }
    const token = authStorage.getAccessToken();
    if (!token) return;
    setGuardando(true);
    setError(null);
    try {
      const actualizada = await academyApi.rename(token, limpio);
      setAcademia(actualizada);
      avanzar({ done: true });
    } catch {
      setError(t('errorGuardar'));
    } finally {
      setGuardando(false);
    }
  }, [nombre, t, avanzar]);

  const guardarMarca = useCallback(async () => {
    const token = authStorage.getAccessToken();
    if (!token) return;
    setGuardando(true);
    setError(null);
    try {
      const actualizado = await themingApi.update(token, { brandHue: hue });
      setTheme(actualizado);
      // Aplica el color en vivo en el resto de la app sin recargar.
      publishThemeUpdate(actualizado);
      avanzar({ done: true });
    } catch {
      setError(t('errorGuardar'));
    } finally {
      setGuardando(false);
    }
  }, [hue, t, avanzar]);

  const terminar = useCallback(async () => {
    await persistir({ ...progreso, completedAt: new Date().toISOString() });
    router.replace('/inicio');
  }, [progreso, persistir, router]);

  const direccion = useMemo(() => {
    if (academia?.primaryHostname) return `https://${academia.primaryHostname}`;
    if (typeof window !== 'undefined') return window.location.origin;
    return '';
  }, [academia]);

  if (cargando) {
    return (
      <Card>
        <CardContent className="p-8 text-center text-muted-foreground">
          {t('guardando')}
        </CardContent>
      </Card>
    );
  }

  const esObligatorio = PASOS_OBLIGATORIOS.includes(paso);
  const pendientes = ONBOARDING_STEPS.filter((p) => progreso.skipped.includes(p) && DESTINOS[p]);

  return (
    <Card>
      <CardContent className="space-y-6 p-8">
        {/* Barra de progreso: saber cuánto queda es la mitad de la calma. */}
        {paso !== 'bienvenida' && paso !== 'resumen' && (
          <div className="space-y-2">
            <p className="text-sm text-muted-foreground">
              {t('progreso', { actual: indice, total: ONBOARDING_STEPS.length - 2 })}
            </p>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
              <div
                className="h-full rounded-full bg-primary transition-all"
                style={{ width: `${(indice / (ONBOARDING_STEPS.length - 2)) * 100}%` }}
              />
            </div>
          </div>
        )}

        {paso === 'bienvenida' && (
          <div className="space-y-6 text-center">
            <h1 className="text-3xl font-bold">{t('bienvenidaTitulo')}</h1>
            <p className="mx-auto max-w-lg text-muted-foreground">{t('bienvenidaCuerpo')}</p>
            <ul className="mx-auto max-w-sm space-y-2 text-left text-sm">
              {[t('bienvenidaPunto1'), t('bienvenidaPunto2'), t('bienvenidaPunto3')].map((p) => (
                <li key={p} className="flex items-start gap-2">
                  <span aria-hidden className="mt-1 text-primary">
                    ✓
                  </span>
                  <span>{p}</span>
                </li>
              ))}
            </ul>
            <Button size="lg" onClick={() => avanzar()}>
              {t('bienvenidaEmpezar')}
            </Button>
          </div>
        )}

        {paso === 'nombre' && (
          <div className="space-y-4">
            <h1 className="text-2xl font-bold">{t('nombreTitulo')}</h1>
            <p className="text-muted-foreground">{t('nombreCuerpo')}</p>
            {academia?.looksAutogenerated && (
              <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">
                {t('nombreAviso', { nombre: academia.name })}
              </p>
            )}
            <div className="space-y-2">
              <Label htmlFor="nombre-academia">{t('nombreEtiqueta')}</Label>
              <Input
                id="nombre-academia"
                value={nombre}
                maxLength={120}
                autoFocus
                placeholder={t('nombrePlaceholder')}
                onChange={(e) => setNombre(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') void guardarNombre();
                }}
              />
            </div>
          </div>
        )}

        {paso === 'marca' && (
          <div className="space-y-4">
            <h1 className="text-2xl font-bold">{t('marcaTitulo')}</h1>
            <p className="text-muted-foreground">{t('marcaCuerpo')}</p>
            <div className="space-y-2">
              <Label htmlFor="color-marca">{t('marcaColor')}</Label>
              <input
                id="color-marca"
                type="range"
                min={0}
                max={360}
                value={hue}
                onChange={(e) => setHue(Number(e.target.value))}
                className="w-full"
                style={{
                  background:
                    'linear-gradient(to right, hsl(0 70% 55%), hsl(60 70% 55%), hsl(120 70% 55%), hsl(180 70% 55%), hsl(240 70% 55%), hsl(300 70% 55%), hsl(360 70% 55%))',
                }}
              />
              <p className="text-xs text-muted-foreground">{t('marcaColorAyuda')}</p>
            </div>
            {/* Vista previa: el color se entiende viéndolo, no leyendo un número. */}
            <div className="rounded-xl border p-4">
              <p className="mb-3 text-xs uppercase tracking-wide text-muted-foreground">
                {t('marcaVista')}
              </p>
              <div className="flex items-center gap-3">
                <div
                  className="grid h-12 w-12 place-items-center rounded-lg font-bold text-white"
                  style={{ backgroundColor: `hsl(${hue} 70% 45%)` }}
                >
                  {(academia?.name ?? 'A').slice(0, 1).toUpperCase()}
                </div>
                <div>
                  <p className="font-semibold">{academia?.name}</p>
                  <p className="text-sm text-muted-foreground">{academia?.primaryHostname}</p>
                </div>
              </div>
            </div>
            <p className="text-xs text-muted-foreground">{t('marcaLogoAyuda')}</p>
          </div>
        )}

        {paso === 'direccion' && (
          <div className="space-y-4">
            <h1 className="text-2xl font-bold">{t('direccionTitulo')}</h1>
            <p className="text-muted-foreground">{t('direccionCuerpo')}</p>
            <div className="flex items-center gap-2 rounded-lg border bg-muted/40 p-3">
              <code className="flex-1 truncate text-sm">{direccion}</code>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  void navigator.clipboard?.writeText(direccion);
                  setCopiado(true);
                  window.setTimeout(() => setCopiado(false), 2000);
                }}
              >
                {copiado ? t('direccionCopiado') : t('direccionCopiar')}
              </Button>
            </div>
            <div className="rounded-lg border p-4">
              <p className="font-semibold">{t('direccionPropioTitulo')}</p>
              <p className="mt-1 text-sm text-muted-foreground">{t('direccionPropioCuerpo')}</p>
            </div>
          </div>
        )}

        {(['curso', 'alumnos', 'cobros', 'correo'] as const).includes(
          paso as 'curso' | 'alumnos' | 'cobros' | 'correo',
        ) && (
          <div className="space-y-4">
            <h1 className="text-2xl font-bold">{t(`${paso}Titulo` as never)}</h1>
            <p className="text-muted-foreground">{t(`${paso}Cuerpo` as never)}</p>
            {(paso === 'cobros' || paso === 'correo') && (
              <p className="text-sm text-muted-foreground">{t(`${paso}Ayuda` as never)}</p>
            )}
            <Button
              variant="outline"
              onClick={() => {
                // Se abre en otra pestaña a propósito: la pantalla de destino ya
                // existe y es completa, y así el asistente no pierde el sitio.
                window.open(DESTINOS[paso] ?? '/inicio', '_blank', 'noopener');
                avanzar({ done: true });
              }}
            >
              {paso === 'cobros'
                ? t('cobrosSi')
                : paso === 'correo'
                  ? t('correoConfigurar')
                  : t('siguiente')}
            </Button>
          </div>
        )}

        {paso === 'resumen' && (
          <div className="space-y-5">
            <h1 className="text-2xl font-bold">
              {t('resumenTitulo', { nombre: academia?.name ?? '' })}
            </h1>
            <p className="text-muted-foreground">{t('resumenCuerpo')}</p>
            {pendientes.length === 0 ? (
              <p className="rounded-lg bg-muted/40 p-3 text-sm">{t('resumenNadaPendiente')}</p>
            ) : (
              <div className="space-y-2">
                <p className="text-xs uppercase tracking-wide text-muted-foreground">
                  {t('resumenPendiente')}
                </p>
                <ul className="space-y-2">
                  {pendientes.map((p) => (
                    <li key={p} className="flex items-center justify-between rounded-lg border p-3">
                      <span className="text-sm">
                        {t(`paso${p.charAt(0).toUpperCase()}${p.slice(1)}` as never)}
                      </span>
                      <a
                        className="text-sm font-semibold text-primary hover:underline"
                        href={DESTINOS[p]}
                      >
                        {t('siguiente')} →
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            <Button size="lg" className="w-full" onClick={() => void terminar()}>
              {t('resumenEntrar')}
            </Button>
          </div>
        )}

        {error && <p className="text-sm text-destructive">{error}</p>}

        {/* Pie de navegación. En «bienvenida» y «resumen» el botón va arriba. */}
        {paso !== 'bienvenida' && paso !== 'resumen' && (
          <div className="flex items-center justify-between gap-3 border-t pt-4">
            <Button variant="ghost" onClick={retroceder} disabled={guardando}>
              {t('atras')}
            </Button>
            <div className="flex items-center gap-2">
              {!esObligatorio && (
                <Button
                  variant="ghost"
                  onClick={() => avanzar({ skipped: true })}
                  disabled={guardando}
                >
                  {t('ahoraNo')}
                </Button>
              )}
              <Button
                onClick={() => {
                  if (paso === 'nombre') return void guardarNombre();
                  if (paso === 'marca') return void guardarMarca();
                  return avanzar({ done: true });
                }}
                disabled={guardando}
              >
                {guardando ? t('guardando') : t('siguiente')}
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
