#!/usr/bin/env tsx
/**
 * license-check.ts — Auditor de licencias de dependencias
 *
 * Lista todas las dependencias del workspace pnpm y reporta su licencia.
 * Falla si encuentra una dependencia con licencia prohibida (GPL/AGPL).
 *
 * Uso:
 *   pnpm tsx scripts/license-check.ts                              # solo reporta
 *   pnpm tsx scripts/license-check.ts --output docs/licensing/third-party-licenses.md
 */

import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const FORBIDDEN_LICENSES = [/^GPL-/i, /^AGPL-/i, /^GPL$/i, /^AGPL$/i];

const REVIEW_REQUIRED = [/MPL/i, /Custom/i, /Proprietary/i, /SSPL/i];

type Dep = {
  name: string;
  version: string;
  license: string;
  path: string;
};

function listDependencies(): Dep[] {
  // Usa pnpm licenses list para obtener un JSON con licencias
  try {
    const raw = execSync('pnpm licenses list --json --recursive', {
      encoding: 'utf8',
      maxBuffer: 1024 * 1024 * 50,
    });
    const parsed = JSON.parse(raw);
    const deps: Dep[] = [];
    for (const license of Object.keys(parsed)) {
      for (const item of parsed[license]) {
        deps.push({
          name: item.name,
          version: item.version,
          license,
          path: item.path ?? '',
        });
      }
    }
    return deps;
  } catch (err: any) {
    console.error('Failed to run "pnpm licenses list":', err.message);
    console.error('Make sure pnpm 9+ is installed and the workspace is bootstrapped.');
    process.exit(2);
  }
}

function classify(license: string): 'forbidden' | 'review' | 'ok' {
  if (FORBIDDEN_LICENSES.some((re) => re.test(license))) return 'forbidden';
  if (REVIEW_REQUIRED.some((re) => re.test(license))) return 'review';
  return 'ok';
}

function main() {
  const args = process.argv.slice(2);
  const outputArg = args.indexOf('--output');
  const outputPath = outputArg >= 0 ? args[outputArg + 1] : null;

  const deps = listDependencies();
  console.log(`license-check: scanning ${deps.length} dependencies...\n`);

  const grouped: Record<string, Dep[]> = {};
  for (const d of deps) {
    if (!grouped[d.license]) grouped[d.license] = [];
    grouped[d.license].push(d);
  }

  let hasForbidden = false;
  for (const license of Object.keys(grouped).sort()) {
    const cls = classify(license);
    const icon = cls === 'forbidden' ? '❌' : cls === 'review' ? '⚠️ ' : '✅';
    console.log(`${icon} ${license} — ${grouped[license].length} package(s)`);
    if (cls === 'forbidden') {
      hasForbidden = true;
      for (const d of grouped[license]) {
        console.log(`   - ${d.name}@${d.version}`);
      }
    }
  }

  if (outputPath) {
    const lines: string[] = [];
    lines.push(`# Third-party licenses inventory\n`);
    lines.push(`> Auto-generated by \`scripts/license-check.ts\`. Do not edit by hand.\n`);
    lines.push(`> Updated: ${new Date().toISOString().slice(0, 10)}\n\n`);
    lines.push(`## Summary\n`);
    lines.push(`Total: **${deps.length}** unique dependencies.\n\n`);
    lines.push(`## By license\n`);
    for (const license of Object.keys(grouped).sort()) {
      lines.push(`### ${license}\n`);
      lines.push(`| Package | Version |`);
      lines.push(`|---------|---------|`);
      for (const d of grouped[license]) {
        lines.push(`| \`${d.name}\` | \`${d.version}\` |`);
      }
      lines.push('');
    }
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, lines.join('\n'), 'utf8');
    console.log(`\n📄 Wrote ${outputPath}`);
  }

  if (hasForbidden) {
    console.error(`\n❌ Forbidden licenses detected (GPL/AGPL). PR blocked.`);
    process.exit(1);
  }

  console.log(`\n✅ No forbidden licenses found.`);
}

main();
