s/\bVolvé\b/Vuelve/g
s/\bvolvé\b/vuelve/g
s/\bIniciá\b/Inicia/g
s/\biniciá\b/inicia/g
s/\bLlamá\b/Llama/g
s/\bllamá\b/llama/g
s/\bRepasá\b/Repasa/g
s/\bRellená\b/Rellena/g
s/\bRefrescá\b/Refresca/g
s/\bRecuperá\b/Recupera/g
s/\bPreguntá\b/Pregunta/g
s/\bOmití\b/Omite/g
s/\bMezclá\b/Mezcla/g
s/\bIndicá\b/Indica/g
s/\bEscaneá\b/Escanea/g
s/\bAsigná\b/Asigna/g
s/\bAprobá\b/Aprueba/g
s/\bAportá\b/Aporta/g
s/nEntrá\b/nEntra/g
