s/\bEmpezá\b/Empieza/g
s/\bInvestigá\b/Investiga/g
s/\binvestigá\b/investiga/g
s/\bPersonalizá\b/Personaliza/g
s/\bpersonalizá\b/personaliza/g
s/\bCurá\b/Cura/g
s/\bcurá\b/cura/g
s/\bModificá\b/Modifica/g
s/\bmodificá\b/modifica/g
s/\bMarcá\b/Marca/g
s/\bmarcá\b/marca/g
s/\bMapeá\b/Mapea/g
s/\bmapeá\b/mapea/g
s/\bInvitá\b/Invita/g
s/\binvitá\b/invita/g
s/\bEtiquetá\b/Etiqueta/g
s/\betiquetá\b/etiqueta/g
s/\bControlá\b/Controla/g
s/\bcontrolá\b/controla/g
s/\bProgramá\b/Programa/g
s/\bprogramá\b/programa/g
s/\bOrganizá\b/Organiza/g
s/\borganizá\b/organiza/g
s/\bVinculá\b/Vincula/g
s/\bvinculá\b/vincula/g
