# Voseo argentino -> español peninsular (tú). Aplicar con: LC_ALL=C.UTF-8 sed -E -f
# Formas con pronombre enclítico (van primero, no colisionan):
s/\bsubilo\b/súbelo/g
s/\bhacelo\b/hazlo/g
s/\bmantenelo\b/mantenlo/g
s/\bmantenelos\b/mantenlos/g
s/\bsolucionalo\b/soluciónalo/g
s/\bSetealo\b/Configúralo/g
s/\bsetealo\b/configúralo/g
# Presente de indicativo (voseo):
s/\btenés\b/tienes/g
s/\bquerés\b/quieres/g
s/\bpodés\b/puedes/g
s/\bmantenés\b/mantienes/g
s/\bnecesitás\b/necesitas/g
# Imperativos terminados en -í:
s/\bDefiní\b/Define/g
s/\bdefiní\b/define/g
s/\bElegí\b/Elige/g
s/\belegí\b/elige/g
s/\bPedí\b/Pide/g
s/\bpedí\b/pide/g
s/\bConfirmá\b/Confirma/g
s/\bconfirmá\b/confirma/g
s/\bEscribí\b/Escribe/g
s/\bescribí\b/escribe/g
s/\bAñadí\b/Añade/g
s/\bañadí\b/añade/g
s/\bSubí\b/Sube/g
s/\bsubí\b/sube/g
s/\bIntroducí\b/Introduce/g
s/\bintroducí\b/introduce/g
# Imperativos terminados en -á:
s/\bmezclá\b/mezcla/g
s/\bGuardá\b/Guarda/g
s/\bguardá\b/guarda/g
s/\bDejá\b/Deja/g
s/\bdejá\b/deja/g
s/\bCreá\b/Crea/g
s/\bcreá\b/crea/g
s/\bIngresá\b/Ingresa/g
s/\bingresá\b/ingresa/g
s/\bSeleccioná\b/Selecciona/g
s/\bseleccioná\b/selecciona/g
s/\bActualizá\b/Actualiza/g
s/\bactualizá\b/actualiza/g
s/\bRevisá\b/Revisa/g
s/\brevisá\b/revisa/g
s/\bConfigurá\b/Configura/g
s/\bconfigurá\b/configura/g
s/\bActivá\b/Activa/g
s/\bactivá\b/activa/g
s/\bVerificá\b/Verifica/g
s/\bverificá\b/verifica/g
s/\bCompletá\b/Completa/g
s/\bcompletá\b/completa/g
s/\bcompletalo\b/complétalo/g
s/\bUsá\b/Usa/g
s/\busá\b/usa/g
s/\bProbá\b/Prueba/g
s/\bprobá\b/prueba/g
s/\bCargá\b/Carga/g
s/\bcargá\b/carga/g
s/\bEnviá\b/Envía/g
s/\benviá\b/envía/g
s/\bCopiá\b/Copia/g
s/\bcopiá\b/copia/g
s/\bPegá\b/Pega/g
s/\bpegá\b/pega/g
s/\baceptá\b/acepta/g
s/\brechazá\b/rechaza/g
s/\bContinuá\b/Continúa/g
s/\bcontinuá\b/continúa/g
s/\bempezá\b/empieza/g
s/\bcomenzá\b/comienza/g
s/\bMandá\b/Manda/g
s/\bmandá\b/manda/g
s/\bBuscá\b/Busca/g
s/\bbuscá\b/busca/g
s/\blimpiá\b/limpia/g
s/\bGestioná\b/Gestiona/g
s/\bgestioná\b/gestiona/g
s/\bEliminá\b/Elimina/g
s/\beliminá\b/elimina/g
s/\breorganizá\b/reorganiza/g
s/\bhablá\b/habla/g
s/\bArrastrá\b/Arrastra/g
s/\barrastrá\b/arrastra/g
s/\bRecordá\b/Recuerda/g
s/\brecordá\b/recuerda/g
s/\bAsegurate\b/Asegúrate/g
s/\basegurate\b/asegúrate/g
s/\bCambiá\b/Cambia/g
s/\bcambiá\b/cambia/g
s/\bEntrá\b/Entra/g
s/\bentrá\b/entra/g
s/\bHacé\b/Haz/g
s/\bhacé\b/haz/g
s/\bPoné\b/Pon/g
s/\bponé\b/pon/g
s/\bMantené\b/Mantén/g
s/\bmantené\b/mantén/g
s/\bajustá\b/ajusta/g
s/\bandá\b/ve/g
