s/\bReintentá\b/Reintenta/g
s/\breintentá\b/reintenta/g
s/\bGenerá\b/Genera/g
s/\bgenerá\b/genera/g
s/\bCopialo\b/Cópialo/g
s/\bcopialo\b/cópialo/g
s/\bAbrí\b/Abre/g
s/\babrí\b/abre/g
s/\bCerrá\b/Cierra/g
s/\bcerrá\b/cierra/g
s/\bAvisá\b/Avisa/g
s/\bavisá\b/avisa/g
s/\bContactá\b/Contacta/g
s/\bcontactá\b/contacta/g
s/\bperdés\b/pierdes/g
s/\bSeteá\b/Configura/g
s/\bseteá\b/configura/g
s/\bLeé\b/Lee/g
s/\bleé\b/lee/g
s/\bTené\b/Ten/g
s/\btené\b/ten/g
s/\bSabé\b/Sabe/g
s/\bsabé\b/sabe/g
s/\bVení\b/Ven/g
s/\bvení\b/ven/g
s/\bSalí\b/Sal/g
s/\bDecí\b/Di/g
s/\bdecí\b/di/g
s/\bSeguí\b/Sigue/g
s/\bseguí\b/sigue/g
s/\bConseguí\b/Consigue/g
s/\bconseguí\b/consigue/g
s/\bAgregá\b/Agrega/g
s/\bagregá\b/agrega/g
s/\bChequeá\b/Comprueba/g
s/\bchequeá\b/comprueba/g
s/\bFijate\b/Fíjate/g
s/\bfijate\b/fíjate/g
s/\bEsperá\b/Espera/g
s/\besperá\b/espera/g
s/\bMirá\b/Mira/g
s/\bmirá\b/mira/g
s/\bAplicá\b/Aplica/g
s/\baplicá\b/aplica/g
s/\bDescargá\b/Descarga/g
s/\bdescargá\b/descarga/g
s/\bImportá\b/Importa/g
s/\bimportá\b/importa/g
s/\bExportá\b/Exporta/g
s/\bexportá\b/exporta/g
s/\bBorrá\b/Borra/g
s/\bborrá\b/borra/g
s/\bPublicá\b/Publica/g
s/\bpublicá\b/publica/g
s/\basigná\b/asigna/g
s/\breemplazá\b/reemplaza/g
s/\bnombrá\b/nombra/g
