/**
 * Copyright (c) VA360 LABS S.L.
 * SPDX-License-Identifier: LicenseRef-Didacta-Sustainable-Use
 */

import {
  Body,
  Controller,
  ForbiddenException,
  Get,
  Logger,
  NotFoundException,
  Put,
  UnauthorizedException,
  UseGuards,
} from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiTags } from '@nestjs/swagger';
import { z } from 'zod';
import { CurrentUser } from '../auth/decorators';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import type { SessionClaims } from '../auth/token.service';
import { ZodValidationPipe } from '../auth/zod-validation.pipe';
import { PrismaService } from '../prisma/prisma.service';

const ADMIN_ROLES = new Set(['super_admin', 'tenant_admin']);

/**
 * El nombre con el que la academia se presenta: sale en el panel, en la firma
 * de los correos a sus alumnos («Equipo {name}») y en la pantalla de acceso.
 *
 * 1..120 igual que el renombrado de super_admin, para que las dos puertas
 * guarden exactamente lo mismo y no haya nombres que una acepte y otra no.
 */
const RenameSchema = z.object({
  name: z.string().trim().min(1).max(120),
});

interface AcademyDto {
  /** Cómo se llama la academia hoy. */
  name: string;
  /** El identificador corto, que también es su subdominio. No se puede cambiar aquí. */
  slug: string;
  /** Su dirección: `academia.didacta.io`, o el dominio propio si ya lo puso. */
  primaryHostname: string | null;
  /**
   * True cuando el nombre sigue siendo el que se dedujo al comprar. Es la señal
   * de que nadie lo ha puesto a mano todavía: al pagar como invitado el nombre
   * sale del correo, así que una academia puede acabar llamándose «valen.ayesa»
   * hasta que su dueño lo cambie.
   */
  looksAutogenerated: boolean;
}

function requireAdmin(user: SessionClaims | undefined): SessionClaims {
  if (!user) throw new UnauthorizedException();
  if (!user.roles.some((r) => ADMIN_ROLES.has(r))) {
    throw new ForbiddenException({
      message: 'Solo super_admin o tenant_admin pueden cambiar los datos de la academia',
      code: 'ADMIN_ACADEMY_FORBIDDEN',
    });
  }
  return user;
}

/**
 * Los datos de identidad de la PROPIA academia de quien llama.
 *
 * Existía `PATCH /admin/tenants/:id`, pero exige `super_admin` porque es la
 * herramienta de gestión entre tenants: recibe un id y puede renombrar
 * cualquiera. El dueño de una academia es `tenant_admin`, así que **no podía
 * ponerle nombre a su propia academia** — y ése es el primer paso del
 * asistente de puesta en marcha.
 *
 * Este controlador no acepta id: opera siempre sobre `claims.tenantId`, el
 * tenant del token. Por construcción no hay forma de tocar el de otro, que es
 * justo la razón por la que el endpoint de super_admin no se podía abrir sin
 * más a `tenant_admin`.
 */
@ApiTags('Admin Academy')
@ApiBearerAuth()
@Controller('admin/tenant-settings/academy')
@UseGuards(JwtAuthGuard)
export class AdminAcademyController {
  private readonly logger = new Logger(AdminAcademyController.name);

  constructor(private readonly prisma: PrismaService) {}

  @Get()
  @ApiOperation({ summary: 'Nombre, identificador y dirección de la academia de quien llama.' })
  async getMine(@CurrentUser() user: SessionClaims | undefined): Promise<AcademyDto> {
    const claims = requireAdmin(user);
    return this.readDto(claims.tenantId);
  }

  @Put()
  @ApiOperation({
    summary:
      'Renombra la PROPIA academia. Solo super_admin o tenant_admin, y siempre sobre su tenant.',
  })
  async rename(
    @CurrentUser() user: SessionClaims | undefined,
    @Body(new ZodValidationPipe(RenameSchema)) body: z.infer<typeof RenameSchema>,
  ): Promise<AcademyDto> {
    const claims = requireAdmin(user);
    await this.prisma.tenant.update({
      where: { id: claims.tenantId },
      data: { name: body.name },
    });
    this.logger.log(
      `Academia ${claims.tenantId} renombrada a "${body.name}" por ${claims.sub ?? 'desconocido'}`,
    );
    return this.readDto(claims.tenantId);
  }

  private async readDto(tenantId: string): Promise<AcademyDto> {
    const tenant = await this.prisma.tenant.findUnique({
      where: { id: tenantId },
      select: { name: true, slug: true },
    });
    if (!tenant) throw new NotFoundException({ code: 'ADMIN_ACADEMY_NOT_FOUND' });

    const domain = await this.prisma.tenantDomain.findFirst({
      where: { tenantId, isPrimary: true },
      select: { hostname: true },
    });

    return {
      name: tenant.name,
      slug: tenant.slug,
      primaryHostname: domain?.hostname ?? null,
      looksAutogenerated: this.looksAutogenerated(tenant.name, tenant.slug),
    };
  }

  /**
   * Heurística deliberadamente conservadora: solo dice «autogenerado» cuando el
   * nombre no aporta nada sobre el slug (es el slug, o el slug con la primera
   * en mayúscula) o cuando parece un correo. Ante la duda, calla: sugerirle a
   * alguien que renombre una academia que ya nombró es peor que no sugerirlo.
   */
  private looksAutogenerated(name: string, slug: string): boolean {
    const limpio = name.trim().toLowerCase();
    if (!limpio) return true;
    if (limpio.includes('@')) return true;
    const desdeSlug = slug.toLowerCase();
    return limpio === desdeSlug || limpio === desdeSlug.replace(/-/g, ' ');
  }
}
