/**
 * Copyright (c) VA360 LABS S.L.
 * SPDX-License-Identifier: LicenseRef-Didacta-Sustainable-Use
 */

import { apiFetch } from './api-client';
import { tenantSettingsApi } from './tenant-settings';

/** Identidad de la academia de quien llama. Ver `AdminAcademyController`. */
export interface Academy {
  name: string;
  slug: string;
  primaryHostname: string | null;
  /** El nombre sigue siendo el deducido al comprar (del correo, típicamente). */
  looksAutogenerated: boolean;
}

export const academyApi = {
  async getMine(bearer: string): Promise<Academy> {
    return apiFetch<Academy>('/api/v1/admin/tenant-settings/academy', { method: 'GET' }, bearer);
  },
  async rename(bearer: string, name: string): Promise<Academy> {
    return apiFetch<Academy>(
      '/api/v1/admin/tenant-settings/academy',
      { method: 'PUT', body: JSON.stringify({ name }) },
      bearer,
    );
  },
};

/** Los pasos del asistente, en el orden en que se recorren. */
export const ONBOARDING_STEPS = [
  'bienvenida',
  'nombre',
  'marca',
  'direccion',
  'curso',
  'alumnos',
  'cobros',
  'correo',
  'resumen',
] as const;

export type OnboardingStep = (typeof ONBOARDING_STEPS)[number];

/**
 * Los pasos que NO se pueden saltar.
 *
 * Decisión de producto: el asistente es bloqueante, pero sólo se exige lo que
 * deja la academia reconocible como suya. Invitar alumnos, crear el primer
 * curso, cobrar y configurar el correo son cosas legítimas de «ahora no»: una
 * academia que aún no tiene alumnos no debería quedar atrapada aquí.
 */
export const PASOS_OBLIGATORIOS: readonly OnboardingStep[] = ['nombre', 'marca'];

export interface OnboardingProgress {
  /** Último paso en el que estaba, para volver donde lo dejó. */
  step: OnboardingStep;
  /** Pasos resueltos, ya sea completándolos o saltándolos. */
  done: OnboardingStep[];
  /** Pasos que dijo «ahora no». Se listan en el resumen como pendientes. */
  skipped: OnboardingStep[];
  /** Timestamp ISO. Mientras sea null, el asistente sigue apareciendo. */
  completedAt: string | null;
}

const SCOPE = 'onboarding';
const KEY = 'academy';

export const VACIO: OnboardingProgress = {
  step: 'bienvenida',
  done: [],
  skipped: [],
  completedAt: null,
};

function normalizar(raw: unknown): OnboardingProgress {
  if (!raw || typeof raw !== 'object') return VACIO;
  const o = raw as Partial<OnboardingProgress>;
  const pasos = new Set<string>(ONBOARDING_STEPS);
  const limpiar = (xs: unknown): OnboardingStep[] =>
    Array.isArray(xs)
      ? (xs.filter((x) => typeof x === 'string' && pasos.has(x)) as OnboardingStep[])
      : [];
  return {
    step:
      typeof o.step === 'string' && pasos.has(o.step) ? (o.step as OnboardingStep) : 'bienvenida',
    done: limpiar(o.done),
    skipped: limpiar(o.skipped),
    completedAt: typeof o.completedAt === 'string' ? o.completedAt : null,
  };
}

/**
 * El progreso vive en el servidor (`tenant_setting`), no en el navegador.
 *
 * Dos razones: si cierra el portátil a mitad, al volver sigue donde estaba
 * aunque entre desde otro sitio; y si la academia tiene dos administradores,
 * el segundo no se encuentra el asistente otra vez porque el primero ya lo
 * hizo. Es estado de la academia, no de la sesión.
 */
export const onboardingApi = {
  async read(): Promise<OnboardingProgress> {
    try {
      const detail = await tenantSettingsApi.get(SCOPE, KEY);
      return normalizar(detail.value);
    } catch {
      // 404 la primera vez, y cualquier otro fallo: se empieza de cero. Nunca
      // se bloquea al admin por no poder leer el progreso.
      return VACIO;
    }
  },
  async write(progress: OnboardingProgress): Promise<void> {
    await tenantSettingsApi.upsert(SCOPE, KEY, { value: progress });
  },
};
